---
version: "3"

services:
  web-nginx:
    image: nginx:alpine
    restart: always
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template
      > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "8000:80"
      - "4430:443"
    depends_on:
      - php
      - mysql
    environment:
      NGINX_HOST: ${NGINX_HOST}
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ./web:/var/www/html
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web:/var/www/html

  composer:
    image: composer:latest
    restart: always
    command: install
    volumes:
      - ./web/app:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: ${MYSQL_HOST}

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    ports:
      - "8989:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db/mysql:/var/lib/mysql

  web-apache2:
    image: ubuntu/apache2:latest
    restart: always
    ports:
      - "8001:80"
      - "4431:443"
    depends_on:
      - php
      - mysql
    volumes:
      - ./etc/ssl:/etc/ssl
      - ./web:/var/www/html
